# SPDX-FileCopyrightText: 2025 Cesium contributors <https://github.com/ForNeVeR/Cesium>
#
# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: ðŸ“ Fetch Sources ðŸ“
        uses: actions/checkout@v5

      - name: ðŸ’¡ Perform Common Steps ðŸ’¡
        uses: ./.github/workflows/perform-common-steps

      - name: ðŸ“¦ Pack Everything ðŸ“¦
        shell: bash
        run: dotnet nuke PackAllCompilerRuntimeSpecificBundles PackCompilerBundleNuPkg PackCompilerTool PackSdk PackTemplates --configuration Release

      - id: version
        name: ðŸ‘€ Get Version ðŸ‘€
        shell: pwsh
        run: echo "version=$(scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)" >> $env:GITHUB_OUTPUT

      - name: âœ… Upload Compiler âœ…
        uses: actions/upload-artifact@v5
        if: runner.os == 'Linux'
        with:
          if-no-files-found: 'error'
          name: Compiler
          path: |-
            ./artifacts/package/release/Cesium.Compiler.Bundle.${{ steps.version.outputs.version }}.nupkg

            ./artifacts/package/release/Cesium.Compiler.Bundle.linux-arm64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.linux-x64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.osx-arm64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.osx-x64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.win-arm64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.win-x64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.win-x86.${{ steps.version.outputs.version }}.zip

            ./artifacts/package/release/Cesium.Compiler.${{ steps.version.outputs.version }}.nupkg
            ./artifacts/package/release/Cesium.Compiler.${{ steps.version.outputs.version }}.snupkg

      - name: âœ… Upload Runtime âœ…
        uses: actions/upload-artifact@v5
        if: runner.os == 'Linux'
        with:
          if-no-files-found: 'error'
          name: Runtime
          path: |-
            ./artifacts/package/release/Cesium.Runtime.${{ steps.version.outputs.version }}.nupkg
            ./artifacts/package/release/Cesium.Runtime.${{ steps.version.outputs.version }}.snupkg

      - name: âœ… Upload SDK âœ…
        uses: actions/upload-artifact@v5
        if: runner.os == 'Linux'
        with:
          if-no-files-found: 'error'
          name: SDK
          path: |-
            ./artifacts/package/release/Cesium.Sdk.${{ steps.version.outputs.version }}.nupkg

      - name: âœ… Upload Templates âœ…
        uses: actions/upload-artifact@v5
        if: runner.os == 'Linux'
        with:
          if-no-files-found: 'error'
          name: Templates
          path: |-
            ./artifacts/package/release/Cesium.Templates.${{ steps.version.outputs.version }}.nupkg

      - name: ðŸ‘€ Read changelog ðŸ‘€
        uses: ForNeVeR/ChangelogAutomation.action@v2
        with:
          output: ./release-notes.md

      - name: âœ… Upload the changelog âœ…
        uses: actions/upload-artifact@v5
        if: runner.os == 'Linux'
        with:
          if-no-files-found: 'error'
          name: release-notes
          path: |-
            ./release-notes.md

      - if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Linux'
        name: ðŸš€ Create a release ðŸš€
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./release-notes.md
          files: |-
            ./artifacts/package/release/Cesium.Compiler.Bundle.${{ steps.version.outputs.version }}.nupkg

            ./artifacts/package/release/Cesium.Compiler.Bundle.linux-arm64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.linux-x64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.osx-arm64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.osx-x64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.win-arm64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.win-x64.${{ steps.version.outputs.version }}.zip
            ./artifacts/package/release/Cesium.Compiler.Bundle.win-x86.${{ steps.version.outputs.version }}.zip

            ./artifacts/package/release/Cesium.Compiler.${{ steps.version.outputs.version }}.nupkg
            ./artifacts/package/release/Cesium.Compiler.${{ steps.version.outputs.version }}.snupkg

            ./artifacts/package/release/Cesium.Runtime.${{ steps.version.outputs.version }}.nupkg
            ./artifacts/package/release/Cesium.Runtime.${{ steps.version.outputs.version }}.snupkg

            ./artifacts/package/release/Cesium.Sdk.${{ steps.version.outputs.version }}.nupkg

            ./artifacts/package/release/Cesium.Templates.${{ steps.version.outputs.version }}.nupkg

          name: Cesium v${{ steps.version.outputs.version }}

      - if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Linux'
        name: ðŸ“¦ Publish Compiler Bundle ðŸ“¦
        run: dotnet nuget push ./artifacts/package/release/Cesium.Compiler.Bundle.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Linux'
        name: ðŸ“¦ Publish Compiler ðŸ“¦
        run: dotnet nuget push ./artifacts/package/release/Cesium.Compiler.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Linux'
        name: ðŸ“¦ Publish Runtime ðŸ“¦
        run: dotnet nuget push ./artifacts/package/release/Cesium.Runtime.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Linux'
        name: ðŸ“¦ Publish SDK ðŸ“¦
        run: dotnet nuget push ./artifacts/package/release/Cesium.Sdk.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Linux'
        name: ðŸ“¦ Publish Templates ðŸ“¦
        run: dotnet nuget push ./artifacts/package/release/Cesium.Templates.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
