name: Run .NET SonarQube analysis
on:
  workflow_dispatch:
jobs:
  run-dotnet-sonarqube-analysis:
    name: Run .NET SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: âš™ Set up JDK 11 âš™
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ğŸ“ Cache SonarCloud packages ğŸ“
        uses: actions/cache@v1
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: ğŸ“ Cache SonarCloud scanner ğŸ“
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: âš™ Setup .NET 6 SDK âš™
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: âš™ Install SonarCloud scanner âš™
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          chmod a+rwx ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: ğŸ” Analyze project ğŸ”
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"ForNeVeR_Cesium" /o:"fornever" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      - name: ğŸ›  Build and analyze ğŸ› 
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        shell: pwsh
#        run: |
#          .\.sonar\scanner\dotnet-sonarscanner begin /k:"ForNeVeR_Cesium" /o:"fornever" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
#          dotnet build
#          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
